import React from 'react'

import { Poppins } from 'next/font/google'

import Navbar from 'src/components/layout/navbar'

// Import global CSS styles
import 'src/styles/globals.css'

import ApolloWrapper from 'src/providers/apollo-provider'
import { SeenProvider } from 'src/providers/seen-provider'

export const metadata = {
  title: 'Pokemon App',
  description: 'Generated by Next.js',
  manifest: '/manifest.json',
}

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap', // Renderiza con una fuente de sistema mientras se carga Poppins
  preload: true, // Pre-carga la fuente para mejorar el primer paint
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
})

interface RootLayoutProps {
  children: React.ReactNode
}
export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" className={`${poppins.variable}`}>
      <head>
        <link rel="preload" href="../styles/globals.css" as="style" />
      </head>
      <body className="min-h-screen bg-body-background">
        <ApolloWrapper>
          <SeenProvider>
            <Navbar />
            <main className="relative mt-[112px] flex min-h-screen flex-col items-center rounded-xl bg-gradient-to-r from-layout-page to-slate-100 p-2 shadow-2xl">
              {children}
            </main>
          </SeenProvider>
        </ApolloWrapper>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </body>
    </html>
  )
}
