import React from 'react';
import Navbar from 'src/components/layout/navbar';
import { Poppins } from 'next/font/google';

import '../styles/globals.css';
import { SeenProvider } from 'src/context/seen-context';
import ApolloWrapper from 'src/context/apollo/apollo-provider';

export const metadata = {
  title: 'Pokemon App',
  description: 'Generated by Next.js',
};

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className={`${poppins.variable}`}>
      <body className='min-h-screen bg-body-background '>
        <ApolloWrapper>
          <SeenProvider>
            <Navbar />
            <main className='relative p-2 mt-[112px] bg-gradient-to-r from-layout-page to-slate-100 rounded-xl flex flex-col items-center min-h-screen shadow-2xl'>
              {children}
            </main>
          </SeenProvider>
        </ApolloWrapper>
        <meta name='viewport' content='width=device-width, initial-scale=1.0' />
      </body>
    </html>
  );
}
